Module4-task1
htmlacademy-javascript/1550703-keksobooking-21 pull request #3
Opened 2020-10-10 16:30 UTC by rmaidveo

2020-10-18 10:16 UTC, StolpnerA requested changes

2020-10-18 10:16 UTC, StolpnerA commented on js/main.js
> +//   });
Почему не нужно?

2020-10-18 10:16 UTC, StolpnerA commented on js/main.js
> +    element[i].setAttribute("disabled", "disabled");
Вообще атрибут `disabled` самостоятельный, т.е. ему не надо писать `disabled = "disabled"`

2020-10-18 10:16 UTC, StolpnerA commented on js/main.js
> +  form.classList.remove('ad-form--disabled');
Не срабатывает :( Все равно форма с `opacity: 0.3;`

2020-10-18 10:16 UTC, StolpnerA commented
Пункт в ТЗ `Заполнение поля адреса`, не соотвествует реалзиации, пересмотри плиз

2020-10-20 11:48 UTC, rmaidveo commented on js/main.js
> +//   });
"метод отрисовки карточки можно закомментировать до тех пор, пока вы не доберётесь до 2-й части задания, чтобы eslint не ругался"

2020-10-26 07:40 UTC, merged